- name: Installing and starting the nginx service
  hosts: web
  tasks:
  - name: Installing the nginx
    ansible.builtin.package:
      name: nginx
      state: present #or installed
  - name: Printing   #Just printing the statement after successful installation
    ansible.builtin.debug:
      msg: "Nginx is installed successfully"
  - name: Starting the nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  