- name: Installing and starting the nginx service
  hosts: web
  tasks:
  - name: Installing the nginx
    ansible.builtin.package:
      name: nginx
      state: present #or installed
  - name: Starting the nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes