- name: Play1
  hosts: web
  tasks:
  - name: Installing the mysql
    ansible.builtin.package:
      name: mysql
      state: present
  - name: Printing successful or not
    ansible.builtin.debug:
      msg: "Installation of mysql is successful"
    
- name: Play2
  hosts: web
  tasks:
  - name: Starting the mysqld service
    ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes
  - name: Printing the starting status
    ansible.builtin.debug:
      msg: "mysqld is started successfully"