- name: Play1
  hosts: web
  tasks:
  - name: Installing the nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: Printing successful or not
    ansible.builtin.debug:
      msg: "Installation of nginx is successful"
    
- name: Play2
  hosts: web
  tasks:
  - name: Starting the nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  - name: Printing the starting status
    ansible.builtin.debug:
      msg: "nginx is started successfully"