- name: Using variables
  hosts: web
  vars: #Play level variable usage
    COURSE: "DEVOPS WITH AWS" #Putting "" is optional
    STUDENT: "MOHANSAI"
    BATCH: "81S"
  tasks:
  - name: Introduction about me right now
    ansible.builtin.debug:
      msg: "Hi I'm {{STUDENT}} , right now learning {{COURSE}} in batch {{BATCH}}"