#Small yaml script to check whether user expense created or not, if not by ignoring the errors will create the user.

- name: Checking whether user is created or not
  hosts: web
  tasks:
  - name: checking expense user created or not
    ansible.builtin.command: id expense #as ansible dont guarantee for all default commands/modules, we can still use command like this
    register: USER #This USER variable will get the output of above command
    ignore_errors: true #as we know we are checking user exists or not, if not it should not display any error and to continue, for this we are ignoring the errors

  - name: Print the USER Info
    ansible.builtin.debug:
      msg: "user info is: {{USER}}"

  - name: creating the user
    ansible.builtin.command: useradd expense
    when: USER.rc != 0
      msg: "Hence user expense is created now successfully"