- name: checking the functions also known as filters
  hosts: web
  become: yes
  tasks:
  - name: Printing variable to which valud is giving by using pipe and default option
    ansible.builtin.debug:
      msg: "{{ time | default ('mama') }}"


- name: Printing given data to upper case
  vars:
  - course: "Hello Ramesh"
  tasks:
  - name: printing to upper
    ansible.builtin.debug:
      msg: "{{ course | upper }}"

  - name: Printing by converting to lower case
    vars:
    - DATA: "HELLO RAMESH"
    ansible.builtin.debug:
      msg: "{{ DATA | lower }}"


  - name: printing unique from provided data or list
    vars:
    - data: "[ 1,2,3,3,4,4,10,100,1 ]"
    ansible.builtin.debug:
      msg: "{{ data | unique }}"
    ansible.builtin.debug:
      msg: "{{ data | duplicate }}"


      