- name: Command vs shell in ansible
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: using command module
    ansible.builtin.command: id ramesh
    register: USER
      #msg: "User ramesh is not existing, kindly create the user to proceed further"
    #when: USER.rc != 0
    ignore_errors: true

  - name: printing the user info
    ansible.builtin.debug:
      msg: "user info is {{ USER }}"

  - name: as user is not existing, going to create in the local means ansible server
    ansible.builtin.command: useradd ramesh
      #msg: "now user info is {{USER}}"
    when: USER.rc != 0
      


#example where command fails in yaml
- name: checking by command
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: checking to append using command
    ansible.builtin.command: ps -ef > /tmp/output.txt


#Using shell this can be done:
- name: checking by command
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: checking to append using command
    ansible.builtin.shell: ps -ef > /tmp/output.txt
