- name: Command vs shell in ansible
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: using command module
    ansible.builtin.command: id ramesh
    register: USER
      #msg: "User ramesh is not existing, kindly create the user to proceed further"
    when: USER.rc != 0
