- name: In this yaml script, we are going to create ec2-instances and then setting r53 records
  hosts: local
  connection: local
  vars:
    sg_id: "sg-0d91387712ba38962"
    subnet_id: "subnet-021ec0b6274b5e769"
    ami_id: "ami-09c813fb71547fc4f"
    zone: mohansai.online
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: creating ec2-instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      vpc_subnet_id: "{{ subnet_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances #after creating provided instances items, their result will get into this ec2_instances

  - name: getting the result of above ec2_instance creation
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"


#now getting r53 private ip addresses for above 3 servers using ec2_instances result
  
  - name: creating or getting the private ips as route53
    amazon.aws.route53:
      state: present
      record: "{{ item.item }}.{{ zone }}" #item.item=mysql/backend/frontend. zone=mohansai.online
      value: "{{ item.instances[0].private_ip_address }}"
      type: A
      ttl: 1
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"


  #now getting / creating the public ip for frontend
  - name: creating or getting the public ip
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}"
      value: "{{ item.instances[0].public_ip_address }}"
      type: A
      ttl: 1
      wait: true
      overwritten: true
    loop: "{{ ec2_instances.results }}"
    when: item.item == "frontend"

