- name: checking usage of dnf and yum
  hosts: web
  tasks:
  - name: Installing nodejs and httpd by dnf
    dnf:
      name: 
      - nodejs
      - httpd
      state: installed
      
      

  # - name: Installing nginx
  #   yum:
  #     name:
  #     - nginx, #To install multiple apps or packages we can use comma or -
  #       mysql
  #     state: installed